apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devworkspaces.devworkspace.kubesphere.io
spec:
  group: devworkspace.kubesphere.io
  names:
    kind: DevWorkspace
    listKind: DevWorkspaceList
    plural: devworkspaces
    singular: devworkspace
    shortNames:
      - dw
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - templateRef
              properties:
                templateRef:
                  type: string
                  description: "引用的 DevWorkspaceTemplate 名称"
                overrides:
                  type: object
                  description: "可选的覆盖配置，允许用户覆盖模板中的某些值"
                  properties:
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                              pattern: '^([0-9]+m?|[0-9]+\.[0-9]+)$'
                            memory:
                              type: string
                              pattern: '^[0-9]+(Gi|Mi|Ki|G|M|K)?$'
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                              pattern: '^([0-9]+m?|[0-9]+\.[0-9]+)$'
                            memory:
                              type: string
                              pattern: '^[0-9]+(Gi|Mi|Ki|G|M|K)?$'
                    storage:
                      type: object
                      properties:
                        size:
                          type: string
                          pattern: '^[0-9]+(Gi|Mi|Ki|G|M|K)?$'
                    ports:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          containerPort:
                            type: integer
                          protocol:
                            type: string
                    environment:
                      type: object
                      properties:
                        image:
                          type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "The current phase of the devworkspace."
                  enum: ["Pending", "Provisioning", "Running", "Stopped", "Failed"]
                message:
                  type: string
                  description: "A human-readable message indicating details about the current phase."
                url:
                  type: string
                podName:
                  type: string
                pvcName:
                  type: string
                serviceName:
                  type: string
      additionalPrinterColumns:
        - name: Template
          type: string
          jsonPath: .spec.templateRef
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: URL
          type: string
          jsonPath: .status.url
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {} 