apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspacetemplates.devworkspace.kubesphere.io
spec:
  group: devworkspace.kubesphere.io
  names:
    kind: WorkspaceTemplate
    listKind: WorkspaceTemplateList
    plural: workspacetemplates
    singular: workspacetemplate
    shortNames:
      - wst
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - displayName
                - environment
              properties:
                displayName:
                  type: string
                  description: "显示名称，在UI上展示的名字"
                description:
                  type: string
                  description: "环境模板的描述信息"
                environment:
                  type: object
                  required:
                    - image
                  properties:
                    image:
                      type: string
                      description: "工作空间使用的容器镜像"
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: '^([0-9]+m?|[0-9]+\.[0-9]+)$'
                        memory:
                          type: string
                          pattern: '^[0-9]+(Gi|Mi|Ki|G|M|K)?$'
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: '^([0-9]+m?|[0-9]+\.[0-9]+)$'
                        memory:
                          type: string
                          pattern: '^[0-9]+(Gi|Mi|Ki|G|M|K)?$'
                storage:
                  type: object
                  properties:
                    size:
                      type: string
                      pattern: '^[0-9]+(Gi|Mi|Ki|G|M|K)?$'
                      default: "10Gi"
                ports:
                  type: array
                  items:
                    type: object
                    required:
                      - containerPort
                    properties:
                      name:
                        type: string
                      containerPort:
                        type: integer
                        minimum: 1
                        maximum: 65535
                      protocol:
                        type: string
                        enum: ["TCP", "UDP"]
                        default: "TCP"
      additionalPrinterColumns:
        - name: DisplayName
          type: string
          jsonPath: .spec.displayName
        - name: Image
          type: string
          jsonPath: .spec.environment.image
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {} 