apiVersion: devworkspace.kubesphere.io/v1alpha1
kind: DevWorkspace
metadata:
  name: my-nodejs-workspace
  namespace: default
spec:
  templateRef: nodejs-16
  overrides:
    ports:
      - name: http
        containerPort: 8080
    resources:
      limits:
        memory: "6Gi" 